version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: deployments/docker/api.Dockerfile
    ports: ["8000:8000"]
    environment:
      - FLASK_ENV=development
      - LOG_LEVEL=INFO

  web:
    image: nginx:stable-alpine
    volumes:
      - ../apps/web/public:/usr/share/nginx/html:ro
      - ./docker/web.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports: ["3000:3000"]
    depends_on:
      - api
