services:
  ollama:
    image: ollama/ollama:0.11.7
    container_name: ollama
    environment:
      OLLAMA_HOST: "0.0.0.0:11434"
      OLLAMA_KEEP_ALIVE: "-1"           # Keep models in memory forever (-1 = infinite)
      OLLAMA_CONTEXT_LENGTH: "4096"
      OLLAMA_ORIGINS: "*"
      OLLAMA_MAX_LOADED_MODELS: "1"     # Optimize for single model
      OLLAMA_LOAD_TIMEOUT: "10m"       # Allow longer load times
    volumes:
      - smartdoc_ollama:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  ollama-init:
    image: ollama/ollama:0.11.7
    container_name: ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    volumes:
      - smartdoc_ollama:/root/.ollama
    # Pull model and warm it up in memory
    entrypoint: ["/bin/sh", "-c"]
    command: [
      "ollama pull gemma3:4b-it-q4_K_M &&
       echo 'Model pulled, warming up...' &&
       echo 'Hello' | ollama run gemma3:4b-it-q4_K_M --verbose &&
       echo 'Model warmed up and ready!'"
    ]
    restart: "no"


  smartdoc:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: smartdoc
    environment:
      FLASK_ENV: production
      LOG_LEVEL: INFO
      SMARTDOC_OLLAMA_BASE_URL: "http://ollama:11434"
      OLLAMA_MODEL: "gemma3:4b-it-q4_K_M"
      SMARTDOC_DB_URL: "sqlite:////data/smartdoc.sqlite3"
    depends_on:
      ollama:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"  # Direct API access
    volumes:
      - smartdoc_data:/data
      - ../apps/web/public:/app/web:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  smartdoc_data:
  smartdoc_ollama:
