[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "smartdoc-shared"
version = "0.1.0"
description = "Shared schemas and utilities for SmartDoc"
authors = [
    {name = "Bruno Sena", email = "bruno.sena@example.com"},
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "ruff>=0.1.0",
    "mypy>=1.5.0",
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
