# Default SmartDoc Configuration

# Application settings
app:
  name: "SmartDoc"
  version: "0.1.0"
  debug: false
  host: "0.0.0.0"
  port: 5000

# Ollama LLM settings
ollama:
  base_url: "http://localhost:11434"
  model: "gemma3:4b-it-q4_K_M"
  timeout: 30

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "system_log.txt"

# Data paths
data:
  raw_path: "./data/raw"
  processed_path: "./data/processed"
  interim_path: "./data/interim"
  cases_path: "./data/raw/cases"

# Session management
session:
  default_timeout: 3600  # 1 hour
  max_sessions: 100
