# Development Configuration
# Inherits from default.yaml and overrides specific settings

app:
  debug: true
  host: "127.0.0.1"
  port: 5000

logging:
  level: "DEBUG"

# Dev-specific Ollama settings (if different)
ollama:
  base_url: "http://localhost:11434"

database:
  url: "sqlite:///smartdoc_dev.sqlite3"
  echo: false
  pool_recycle: 1800
