# Production Configuration
# Inherits from default.yaml and overrides for production

app:
  debug: false
  host: "0.0.0.0"
  port: 8000

logging:
  level: "WARNING"
  file: "/var/log/smartdoc/application.log"

# Production Ollama settings
ollama:
  base_url: "http://ollama-service:11434"
  timeout: 60

database:
  url: "sqlite:////var/smartdoc/data/prod.sqlite3" # or postgres+psycopg2://user:pass@host/db
  echo: false
  pool_recycle: 1800
